@api = http://localhost:5000

GET {{api}}/tutorial/rp
Content-Type: application/json

[
        {
            "name": "Simon",
            "lastname": "Cieza",
            "email": "sc@gmail.com",
            "password": "passone",
            "phone": "991",
            "kind": "1"
        }
]